services:
  - type: web
    name: inventory-backend
    env: node
    region: london
    plan: free
    buildCommand: |
      cd server && 
      npm install && 
      npx prisma generate && 
      npx prisma migrate deploy --verbose && 
      npx prisma db seed && 
      npm run build
    startCommand: |
      cd server &&
      npx prisma migrate deploy && 
      node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
