services:
  - type: web
    name: inventory-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      cd server && 
      npm install && 
      npx prisma generate && 
      npx prisma migrate deploy && 
      npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false