services:
  - type: web
    name: inventory-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      cd server &&
      npm install &&
      npx prisma generate &&
      npx prisma migrate deploy --verbose &&
      npm run build &&
      npm run db:seed

    startCommand: |
      cd server &&
      node dist/src/index.ts
    envVars:
      - key: DATABASE_URL
        sync: false