services:
  - type: web
    name: inventory-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      cd server && 
      npm install && 
      npx prisma generate && 
      npm run build
    startCommand: |
      cd server &&
      npx prisma migrate deploy && 
      npm run db:seed && 
      npm start
    envVars:
      - key: DATABASE_URL
        sync: false