FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies (including dev deps)
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Global tools (optional, but helpful for dev)
RUN npm install -g ts-node nodemon concurrently

# Copy the rest of backend 
COPY . .

# Copy Prisma schema and generate client
# COPY prisma ./prisma
RUN npx prisma generate



# Expose port
EXPOSE 4000

# Start with nodemon for hot reloading
CMD ["npm", "run", "dev"]